language: node_js
node_js:
  - v8
script:
  - yarn lint
  - yarn flow
  - yarn ts-check
  - yarn match-snapshot
  - yarn build
  - yarn test
after_script:
  - 'npm run coveralls'

# blocklist version commits
branches:
  except:
    - /^v[0-9]/
